AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda function

Globals:
  Api:
    Cors:
      AllowHeaders: "'Content-Type'"
      AllowMethods: "'OPTIONS, POST'"
      AllowOrigin: "'*'"
  Function:
    MemorySize: 256
    Timeout: 60

Resources:
  PrerenderApi:
    Type: AWS::Serverless::Function
    Properties:
      Description: Prerender API
      PackageType: Image
      AutoPublishAlias: Auto
      Environment:
        Variables:
          PRERENDER_DEBUG: false
      Events:
        Detect:
          Type: Api
          Properties:
            Method: post
            Path: /
      Role: !GetAtt LambdaRole.Arn
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./

  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref PrerenderApi
      AuthType: NONE
      Cors:
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - POST
        AllowOrigins:
          - '*'
        ExposeHeaders:
          - Cache-Control
          - Content-Type
      InvokeMode: BUFFERED

  LambdaFunctionUrlPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PrerenderApi
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-prerenderApi
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AdministratorAccess

  CloudFrontConfig:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Prerender API
        Enabled: true
        Origins:
          -
            Id: prerenderApi
            DomainName: aws.amazon.com
            CustomOriginConfig:
              HTTPPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: prerenderApi
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        CacheBehaviors:
          -
            TargetOriginId: prerenderApi
            PathPattern: '/*'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            ForwardedValues:
              Headers:
                - Accept
                - Authorization
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: allow-all
