name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - uses: actions/checkout@v4

      # Chrome environment
      - name: Install Chrome binary
        run: curl -L https://github.com/nuxy/chromium-lambda-build/releases/download/0.0.1/headless_shell.tar.gz | tar -xz -C .

      # Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run Mocha
        run: npm run test
